export function buttonTemplate(): string {
  return `import * as React from "react";

/**
 * Accessible button component with design system tokens.
 * Supports multiple variants and maintains WCAG AA contrast requirements.
 */

type ButtonVariant = "primary" | "secondary" | "outline";

type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  /** Visual style variant. Defaults to "primary" */
  variant?: ButtonVariant;
};

export function Button({ 
  children, 
  variant = "primary", 
  style,
  ...props 
}: ButtonProps) {
  const [isHovered, setIsHovered] = React.useState(false);
  const [isFocused, setIsFocused] = React.useState(false);

  // Variant-specific styles
  const variantStyles = {
    primary: {
      background: isHovered 
        ? "var(--color-accentHover)" 
        : "var(--color-accent)",
      color: "var(--color-onAccent)",
      border: "1px solid var(--color-accent)",
    },
    secondary: {
      background: isHovered 
        ? "color-mix(in srgb, var(--color-bgCard) 94%, white)" 
        : "var(--color-bgCard)",
      color: "var(--color-text)",
      border: "1px solid var(--color-border)",
    },
    outline: {
      background: isHovered 
        ? "color-mix(in srgb, var(--color-accent) 12%, transparent)" 
        : "transparent",
      color: "var(--color-accent)",
      border: "1px solid var(--color-accent)",
    },
  };

  return (
    <button
      {...props}
      onMouseEnter={(e) => {
        setIsHovered(true);
        props.onMouseEnter?.(e);
      }}
      onMouseLeave={(e) => {
        setIsHovered(false);
        props.onMouseLeave?.(e);
      }}
      onFocus={(e) => {
        setIsFocused(true);
        props.onFocus?.(e);
      }}
      onBlur={(e) => {
        setIsFocused(false);
        props.onBlur?.(e);
      }}
      style={{
        ...variantStyles[variant],
        borderRadius: "var(--radius-md)",
        padding: "0.6rem 1rem",
        fontSize: "var(--font-size-base)",
        lineHeight: "var(--line-height-base)",
        cursor: "pointer",
        // Smooth transitions for hover/focus states
        transition: "all 0.2s ease-in-out",
        // Focus ring for keyboard navigation
        outline: isFocused ? "2px solid var(--color-accent)" : "none",
        outlineOffset: isFocused ? "2px" : "0",
        // Merge user-provided styles
        ...style,
      }}
    >
      {children}
    </button>
  );
}
`;
}

export function inputTemplate(): string {
  return `import * as React from "react";

/**
 * Accessible input component with design system tokens.
 * Maintains WCAG AA contrast and provides clear focus indicators.
 * 
 */

type InputProps = React.InputHTMLAttributes<HTMLInputElement>;

export function Input({ style, ...props }: InputProps) {
  const [isFocused, setIsFocused] = React.useState(false);

  return (
    <input
      {...props}
      onFocus={(e) => {
        setIsFocused(true);
        props.onFocus?.(e);
      }}
      onBlur={(e) => {
        setIsFocused(false);
        props.onBlur?.(e);
      }}
      style={{
        background: "var(--color-bgCard)",
        color: "var(--color-text)",
        border: isFocused 
          ? "1px solid var(--color-accent)" 
          : "1px solid var(--color-border)",
        borderRadius: "var(--radius-md)",
        padding: "0.55rem 0.75rem",
        fontSize: "var(--font-size-base)",
        lineHeight: "var(--line-height-base)",
        // Smooth border transition
        transition: "border-color 0.2s ease-in-out",
        // Focus ring for keyboard navigation (WCAG 2.4.7)
        outline: isFocused ? "2px solid var(--color-accent)" : "none",
        outlineOffset: isFocused ? "2px" : "0",
        // Merge user-provided styles
        ...style,
      }}
    />
  );
}
`;
}

export function componentsIndexTemplate(): string {
  return `/**
 * Design System Components
 * Generated by A11Y Design System Generator
 * 
 * All components follow WCAG 2.2 AA standards
 * and use CSS variables from theme.css
 */

export { Button } from "./Button";
export { Input } from "./Input";
`;
}

export function tailwindConfigTemplate(): string {
  return `/** 
 * Tailwind CSS Configuration
 * Generated by A11Y Design System Generator
 * 
 * This config extends Tailwind with your design system tokens.
 * Make sure to import theme.css in your app for CSS variables to work.
 * 
 * @type {import('tailwindcss').Config} 
 */
module.exports = {
  content: ["./src/**/*.{ts,tsx,js,jsx,html}"],
  theme: {
    extend: {
      // Color tokens (WCAG AA contrast guaranteed)
      colors: {
        bg: "var(--color-bg)",
        bgCard: "var(--color-bgCard)",
        text: "var(--color-text)",
        textSecondary: "var(--color-textSecondary)",
        accent: "var(--color-accent)",
        accentHover: "var(--color-accentHover)",
        onAccent: "var(--color-onAccent)",
      },
      // Border color with semantic default
      borderColor: {
        DEFAULT: "var(--color-border)",
      },
      // Border radius tokens
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
      },
      // Fluid typography (responsive)
      fontSize: {
        base: "var(--font-size-base)",
      },
      lineHeight: {
        base: "var(--line-height-base)",
      },
      // Shadow token
      boxShadow: {
        soft: "var(--shadow-soft)",
      },
    },
  },
  plugins: [],
};
`;
}
